import mysql.connector as c

def f():
 m=c.connect(host="localhost",user="root",passwd="1234",database="movie_mania")
 my=m.cursor()
 my.execute("create table m_movie (Movie varchar(30) primary key,Year int,Type varchar(10),Actor varchar(20),Actress varchar(20))")


def f1():
 m=c.connect(host="localhost",user="root",passwd="1234",database="movie_mania")
 my=m.cursor()
 my.execute("show tables")
 for i in my:
  print(i)
def f2():
 m=c.connect(host="localhost",user="root",passwd="1234",database="movie_mania")
 my=m.cursor()
 my.execute("desc m_movie")
 for i in my:
  print(i)

def f3():
 m=c.connect(host="localhost",user="root",passwd="1234",database="movie_mania")
 my=m.cursor()
 my.execute("insert into m_movie values('WAR',2019,'Bollywood','Hrithik Roshan','Vaani Kapoor')")
 my.execute("insert into movie values('GODZILLA',2014,'Hollywood','Aaron Taylor Johnson','Elizabeth Olsen')") 
 my.execute("insert into m_movie values('KHILADIYON KA KHILADI',1996,'Bollywood','Akshay Kumar','Raveena Tandon')")
 my.execute("insert into m_movie values('NEXT',2007,'Hollywood','Nicolas Cage','Jessica Biel')")
 my.execute("insert into m_movie values('GULLY BOY',2019,'Bollywood','Ranveer Singh','Alia Bhatt')")
 my.execute("insert into m_movie values('HOSTAGE',2005,'Hollywood','Bruce Willis','Michelle Horn')")
 my.execute("insert into m_movie values('AAR YA PAR',1997,'Bollywood','Jackie Shroff','Deepa Sahi')")
 my.execute("insert into m_movie values('VALKYRIE',2008,'Hollywood','Tom Cruise','Carice Van Houten')")
 my.execute("insert into m_movie values('BHARAT',2019,'Bollywood','Salman Khan','Katrina Kaif')")
 my.execute("insert into m_movie values('HANCOCK',2008,'Hollywood','Will Smith','Charlize Theron')")
 my.execute("insert into m_movie values('KARAN ARJUN',1995,'Bollywood','Salman Khan','Kajol')")
 my.execute("insert into m_movie values('FEARLESS',2017,'Hollywood','Jonathan Forbes','Helen McCrory')")
 my.execute("insert into m_movie values('KABIR SINGH',2019,'Bollywood','Shahid Kapoor','Kiara Advani')")
 my.execute("insert into m_movie values('CONSTANTINE',2005,'Hollywood','Keanu Reeves','Rachel Weisz')")
 my.execute("insert into m_movie values('AADMI KHILONA HAI',1993,'Bollywood','Govinda','Reena Roy')")
 my.execute("insert into m_movie values('SALT',2010,'Hollywood','Liev Schreiber','Angelina Jolie')")
 my.execute("insert into m_movie values('GOOD NEWWZ',2019,'Bollywood','Akshay Kumar','Kareena Kapoor Khan')")
 my.execute("insert into m_movie values('JUMPER',2008,'Hollywood','Hayden Christensen','Rachel Bilson')")
 my.execute("insert into m_movie values('KUCH KUCH HOTA HAI',1998,'Bollywood','Shah Rukh Khan','Kajol')")
 my.execute("insert into m_movie values('HITMAN',2007,'Hollywood','Timothy Olyphant','Olga Kurylenko')")
 my.execute("insert into m_movie values('BABY',2015,'Bollywood','Akshay Kumar','Taapsee Pannu')")
 my.execute("insert into m_movie values('ERAGON',2006,'Hollywood','Jeremy Irons','Sienna Guillory')")
 my.execute("insert into m_movie values('FARISHTAY',1991,'Bollywood','Dharmendra','Sri Devi')")
 my.execute("insert into m_movie values('SAHARA',2005,'Hollywood','Matthew McConaughey','Penelope Cruz')")
 my.execute("insert into m_movie values('BAJIRAO MASTANI',2015,'Bollywood','Ranveer Singh','Deepika Padukone')")
 my.execute("insert into m_movie values('DOOM',2005,'Hollywood','Dwayne Johnson','Rosamund Pike')")
 my.execute("insert into m_movie values('YAADEIN',2001,'Bollywood','Hrithik Roshan','Kareena Kapoor')")
 my.execute("insert into m_movie values('MOON',2009,'Hollywood','Sam Rockwell','Dominique McElligott')")
 my.execute("insert into m_movie values('GABBAR IS BACK',2015,'Bollywood','Akshay Kumar','Shruti Haasan')")
 my.execute("insert into m_movie values('THIS IS WHERE I LEAVE YOU',2014,'Hollywood','Jason Bateman','Jane Fonda')")
 my.execute("insert into m_movie values('KHAKEE',2004,'Bollywood','Amitabh Bachchan','Aishwarya Rai')")
 my.execute("insert into m_movie values('THE GREATEST SHOWMAN',2017,'Hollywood','Hugh Jackamn','Michelle Ferguson')")
 my.execute("insert into m_movie values('BOMBAY VELVET',2015,'Bollywood','Ranbir Kapoor','Anushka Sharma')")
 my.execute("insert into m_movie values('THE UGLY TRUTH',2009,'Hollywood','Gerard Butler','Katherine Heigl')")
 my.execute("insert into m_movie values('PIKU',2015,'Bollywood','Amitabh Bachchan','Deepika Padukone')")
 my.execute("insert into m_movie values('DEAD POETS SOCIETY',1989,'Hollywood','Robin Williams','Chris Noel')")
 my.execute("insert into m_movie values('APNE',2007,'Bollywood','Sunny Deol','Shilpa Shetty')")
 my.execute("insert into m_movie values('GREEN BOOK',2018,'Hollywood','Viggo Mortensen','Linda Cardellini')")
 my.execute("insert into m_movie values('SHAAPIT',2010,'Bollywood','Aditya Narayan','Shweta Agarwal')")
 my.execute("insert into m_movie values('THE SHAWSHANK REDEMPTION',1994,'Hollywood','Tim Robbins','Renee Blaine')")
 my.execute("insert into m_movie values('WANTED',2009,'Bollywood','Salman Khan','Ayesha Takia')")
 my.execute("insert into m_movie values('THE SPACE BETWEEN US',2017,'Hollywood','Asa Butterfield','Britt Roberston')")
 my.execute("insert into m_movie values('HOUSEFULL',2010,'Bollywood','Akshay Kumar','Deepika Padukone')")
 my.execute("insert into m_movie values('INTERSTELLAR',2004,'Hollywood','Matthew McConaughey','Anne Hathaway')")
 my.execute("insert into m_movie values('PK',2014,'Bollywood','Aamir Khan','Anushka Sharma')")
 my.execute("insert into m_movie values('CRASH',2004,'Hollywood','Matt Dillon','Thandie Newton')")
 my.execute("insert into m_movie values('RAAJNEETI',2010,'Bollywood','Ajay Devgn','Katrina Kaif')")
 my.execute("insert into m_movie values('SNATCH',2000,'Hollywood','Brad Pitt','Nicola Collins')")
 my.execute("insert into m_movie values('RAABTA',2017,'Bollywood','Sushant Singh','Kriti Sanon')")
 my.execute("insert into m_movie values('JOKER',2019,'Hollywood','Joaquin Phoenix','Zazie Beetz')")
 my.execute("insert into m_movie values('I HATE LUV STORYS',2010,'Bollywood','Imran Khan','Sonam Kapoor')")
 my.execute("insert into m_movie values('JAWS',1975,'Hollywood','Roy Scheider','Lorraine Gary')")
 my.execute("insert into m_movie values('READY',2011,'Bollywood','Salman Khan','Kangana Ranaut')")
 my.execute("insert into m_movie values('ALIEN',1979,'Hollywood','John Hurt','Sigourney Weaver')")
 my.execute("insert into m_movie values('GUZAARISH',2010,'Bollywood','Hrithik Roshan','Aishwarya Rai')")
 my.execute("insert into m_movie values('TITANIC',1997,'Hollywood','Leonardo DiCaprio','Kate Winslet')")
 my.execute("insert into m_movie values('ENGLISH VINGLISH',2012,'Bollywood','Amitabh Bachchan','Sridevi')")
 my.execute("insert into m_movie values('JURASSIC PARK',1993,'Hollywood','Sam Neill','Laura Dern')")
 my.execute("insert into m_movie values('BULANDI',2000,'Bollywood','Rajinikanth','Rajinikanth')")
 my.execute("insert into m_movie values('AVATAR',2009,'Hollywood','Sam Worthington','Zoe Saldana')")
 my.execute("insert into m_movie values('SULTAN',2016,'Bollywood','Salman Khan','Anushka Sharma')")
 my.execute("insert into m_movie values('GLADIATOR',2000,'Hollywood','Joaquin Phoenix','Connie Nielsen')")
 my.execute("insert into m_movie values('DHADKAN',2000,'Bollywood','Akshay Kumar','Shilpa Shetty')")
 my.execute("insert into m_movie values('INCEPTION',2010,'Hollywood','Leonardo DiCaprio','Ellen Page')")
 my.execute("insert into m_movie values('PADMAAVAT',2018,'Bollywood','Shahid Kapoor','Deepika Padukone')")
 my.execute("insert into m_movie values('MEMENTO',2000,'Hollywood','Guy Pearce','Carrie-Anne Moss')")
 my.execute("insert into m_movie values('DIL PE MAT LE YAAR',2000,'Bollywood','Manoj Bajpai','Tabu')")
 my.execute("insert into m_movie values('UP',2009,'Hollywood','Edward Asner','Mickie McGowan')")
 my.execute("insert into m_movie values('HIMMATWALA',2013,'Bollywood','Ajay Devgn','Tamannah')")
 my.execute("insert into m_movie values('AIRPLANE',1980,'Hollywood','Jim Abrahams','Julie Hagerty')")
 m.commit()
def f4():
 m=c.connect(host="localhost",user="root",passwd="1234",database="movie_mania")
 my=m.cursor() 
 my.execute("select * from m_movie")
 for i in my:
     print(i)
